---
title: "IBD data processing"
author: "Mikhail Dozmorov"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: no
  html_document:
    theme: cerulean
    toc: yes
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Set up the environment
library(knitr)
opts_chunk$set(cache.path='cache/', fig.path='img/', cache=F, tidy=T, fig.keep='high', echo=F, dpi=100, warnings=F, message=F, comment=NA, warning=F, results='as.is', fig.width = 10, fig.height = 6) #out.width=700, 
library(pander)
panderOptions('table.split.table', Inf)
set.seed(1)
library(dplyr)
options(stringsAsFactors = FALSE)
```

```{r libraries}
library(phyloseq)
library(biomformat)
library(dplyr)
library(readr)
library(magrittr)
source("https://raw.githubusercontent.com/mdozmorov/MDmisc/master/R/venn.R")
```


```{r settings}
# Data folder
# dataDir <- "/Users/mdozmorov/Documents/Data/GitHub/HMP2/"
dataDir <- "D:/HMP2/"
# Use phyloseq or low-level reading of BIOM files
phyloseq_import_biom <- FALSE # If FALSE, `read_biom` will be used
# File names
fileNameIn1  <- "data_IBD_new/taxonomic_profiles.tsv"       # OTU table
fileNameIn2  <- "data_IBD_new/hmp2_metadata.csv"            # Metadata
fileNameOut1 <- "data.IBD/files_16S_unreadable.txt"         # Unreadable 16S files
# Files for matching filenames
fileNameOut2 <- "data.IBD/files_16S_actual_only.txt"        # Downloaded, but no annotations
fileNameOut3 <- "data.IBD/files_16S_listed_only.txt"        # Annotated, but not downloaded
fileNameOut4 <- "data.IBD/files_16S_actual_and_listed.txt"  # Downloaded AND Annotated
# Files for saving the results
fileNameOut5 <- "data_IBD_new/IBD16S_mtx.rda"  # BIOM data
fileNameOut6 <- "data_IBD_new/IBD16S_samp.rda" # Annotation data
fileNameOut7 <- "data_IBD_new/IBD16S_tax.rda"  # Taxonomy data
```

```{r}
mtx1 <- read_csv(fileNameIn2) # Metadata
mtx1 %<>% arrange(`External ID`)  # Sort by sample_id
# Convert to data.frame
mtx1 <- as.data.frame(mtx1)
```


```{r}
# Read in OTU table
mtx_biom <- read_tsv(fileNameIn1) %>% as.data.frame()
# Set Taxa IDs as rownames
rownames(mtx_biom) <- mtx_biom$`#OTU ID`
# Drop OTU ID column
mtx_biom <- mtx_biom[,-1]
# Create taxonomy table
mtx_tax_table <- mtx_biom$taxonomy
mtx_tax_table <- read.table(text = mtx_tax_table, sep = ';') # Split into data.frame wiith column for each classifier
# Remove underscores
mtx_tax_table <- apply(mtx_tax_table, 2, function(x) gsub("_", "", x))
mtx_tax_table <- apply(mtx_tax_table, 2, function(x) gsub(" ", "", x))
# Set rownames & colnames
rownames(mtx_tax_table) <- rownames(mtx_biom)
colnames(mtx_tax_table) <- c("Kingdom", 'Phylum', 'Class', 'Order', 'Family', 'Genus')
# Drop taxonomy column from mtx_biom
mtx_biom <- mtx_biom[, -179]
# convert OTU table to numeric matrix
mtx_biom <- as.matrix(mtx_biom)
```

```{r}
# Subset metadata to only samples present in OTU table
mtx1 <- mtx1[mtx1$`External ID` %in% colnames(mtx_biom), ]
# Arrange samples
mtx_biom <- mtx_biom[, order(colnames(mtx_biom))]
mtx1 <- mtx1[order(mtx1$`External ID`), ]
# Check IDs match
all.equal(mtx1$`External ID`, colnames(mtx_biom))
# Set rownames for sample data
rownames(mtx1) <- mtx1$`External ID`
# Change sample data column names to match with other datasets
colnames(mtx1)[471] <- "subject_race"
colnames(mtx1)[9] <- "visit_number"
colnames(mtx1)[459] <- "subject_gender"
colnames(mtx1)[2] <- "subject_id"
# Change capitalization of levels
mtx1$subject_gender <- sub("Female", "female", mtx1$subject_gender)
mtx1$subject_gender <- sub("Male", "male", mtx1$subject_gender)
# Since none of the races fall into categories of other dataset just set all to uknown
mtx1$subject_race <- "unknown"
```



```{r}
# Check overlap between Greengenes IDs and BIOM IDs
# mtx_venn <- Venn2(rownames(mtx_tax_table), rownames(mtx_biom), c("Greengenes", "biom"))
setdiff(rownames(mtx_biom), rownames(mtx_tax_table)) # Should be 0
intersect(rownames(mtx_biom), rownames(mtx_tax_table)) %>% length

# Subset and match the taxonomy table to the BIOM table
mtx_tax_table <- mtx_tax_table[ rownames(mtx_tax_table) %in% rownames(mtx_biom), ]
mtx_tax_table <- mtx_tax_table[ match(rownames(mtx_biom), rownames(mtx_tax_table)), ]
all.equal(rownames(mtx_biom), rownames(mtx_tax_table))
```


```{r}
# Rename matrices for the package
IBD16S_mtx  <- mtx_biom
IBD16S_samp <- mtx1
IBD16S_tax  <- mtx_tax_table
# Save them
save(IBD16S_mtx,  file = fileNameOut5) # BIOM data
save(IBD16S_samp, file = fileNameOut6) # Annotation data
save(IBD16S_tax,  file = fileNameOut7) # Taxonomy data
```

Data dimensions for the first version of the package

```
> dim(IBD16S_mtx)
[1] 1777 1435
> dim(IBD16S_samp)
[1] 1435   11
> dim(IBD16S_tax)
[1] 1777    7
```

Data dimensions, current

```{r echo=TRUE}
# Check dimensions
dim(IBD16S_mtx)
dim(IBD16S_samp)
dim(IBD16S_tax)
```

