---
title: "read IBD and T2D biom files"
author: "author"
date: "January 11, 2019"
output: html_document
---

# T2D

```{r}
library(phyloseq)
library(dplyr)
library(readr)
library(magrittr)


# Input files
fileNameIn1  <- "data.T2D/hmp_cart_50199a791.tsv" # Manifest
fileNameIn2  <- "data/hmp_cart_metadata_12019e21a0.tsv" # Metadata
files <- list.files("data.T2D/t2d")
green <- read.table("data/gg_13_5_taxonomy.txt", sep = "\t")

# Manifest
mtx1 <- read_tsv(fileNameIn1)
# Add file names
mtx1 %<>% mutate(file_name = sapply(mtx1$urls, function(x) strsplit(x, split = ",", fixed = TRUE)[[1]][1] %>% basename) %>% unname)

# Sanity check: Are they all in the manifest?
all.equal(files %>% basename %>% sort, mtx1$file_name %>% sort)

phylo_list <- list()

for(i in 1:length(files)) {
  phylo_list[[i]] <- import_biom(paste0("data.T2D/t2d/", files[i]))
}


# Merge data
mat <- otu_table(phylo_list[[1]])
mat <- data.frame(taxa = as.numeric(rownames(mat)), counts = mat[,1])
for (i in 2:length(phylo_list)) {
  tmp <- otu_table(phylo_list[[i]])
  tmp <- data.frame(taxa = as.numeric(rownames(tmp)), counts = tmp[,1])
  mat <- full_join(mat, tmp, by = c("taxa" = "taxa"))
}

rownames(mat) <- mat$taxa
colnames(mat)[-1] <- files
mat[is.na(mat)] <- 0
mat.taxa <- mat$taxa
mat <- mat[,-1]
mat <- as.matrix(mat)
# get which files are in metadata
idx <- match(files, mtx1$file_name)


```

## Tax table


```{r}
# Make taxonomy table
# Get taxonomy column
mtx_tax_table <- as.character(green$V2)
# Split the combined strings, and combine them into data frame
mtx_tax_table <- sapply(mtx_tax_table, function(x) strsplit(x, "; ")) %>% unname %>% do.call(rbind, .)


# A function to take column i, extract taxa level prefix, return unique prefixes
# Made for sanity check - each column should return only one taxa level ID
check_taxa_level <- function(mtx_tax_table, i) {
  sapply(mtx_tax_table[, i], function(x) strsplit(x, "__")[[1]][1]) %>% unname %>% unique
}
# Actually do sanity check - should be single letters corresponding to
# Kingdom   Phylum          Class          Order          Family          Genus        Species
for (i in 1:ncol(mtx_tax_table)) {
  check_taxa_level(mtx_tax_table = mtx_tax_table, i) %>% print
}

# A function to take a column and remove taxa level prefix from it
prune_taxa_level <- function(column) {
  sapply(column, function(x) strsplit(x, "__")[[1]][2]) %>% unname
}
# Actually remove prefixes from the columns
mtx_tax_table <- apply(mtx_tax_table, 2, function(x) prune_taxa_level(x))

# Attach column and row names
colnames(mtx_tax_table) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species") # Fixed names
rownames(mtx_tax_table) <- green$V1 # Greengene IDs
mtx_tax_table[1:5, 1:5]
```

## make phyloseq object

```{r}
meta <- as.data.frame(mtx1[idx,])
rownames(meta) <- meta$file_name

otu <- otu_table(mat, taxa_are_rows = TRUE)
samp <- sample_data(meta)

# order everything
tax.idx <- match(rownames(mtx_tax_table), rownames(mat))
tax.idx <- tax.idx[!is.na(tax.idx)]
taxa <- mtx_tax_table[tax.idx,]

T2D_phyloseq <- phyloseq(otu, samp, taxa)
save(T2D_phyloseq, file = "data/hmp2_phyloseq_16S_T2D.rda")
```



# IBD

```{r}
library(phyloseq)
library(dplyr)
library(magrittr)
library(readr)


options(stringsAsFactors = FALSE)

# Input files
fileNameIn1  <- "data.IBD/hmp_cart_2bcd863c2e.tsv" # Manifest
fileNameIn2  <- "data/hmp_cart_metadata_35c73e52bd.tsv" # Metadata
# files <- list.files("data.IBD/ibd")
load('data/ibd_readable_files.rda')
green <- read.table("data/gg_13_5_taxonomy.txt", sep = "\t")

# Manifest
mtx1 <- read_tsv(fileNameIn1)
# Add file names
mtx1 %<>% mutate(file_name = sapply(mtx1$urls, function(x) strsplit(x, split = ",", fixed = TRUE)[[1]][1] %>% basename) %>% unname)
meta <- mtx1

# Sanity check: Are they all in the manifest?
all.equal(files %>% basename %>% sort, mtx1$file_name %>% sort)

phylo_list <- list()

for(i in 1:length(files)) {
  res <- try(phylo_list[[i]] <- import_biom(paste0("data.IBD/ibd/", files[i])), TRUE)
  if(isTRUE(class(res)=="try-error")) { next } else {phylo_list[[i]] <- res}
  # print(i)
}


# # get unreadable files
# unreadable <- sapply(phylo_list, is.null) # 8 unreadable files
# # update files list with only files that were read
# files <- files[!unreadable]
# save(files, file = 'data/ibd_readable_files.rda')
# phylo_list <- phylo_list[!unreadable]

# Merge data
# mat <- otu_table(phylo_list[[1]])
# mat <- data.frame(taxa = as.numeric(rownames(mat)), counts = mat[,1])
# # phylo_list <- lapply(phylo_list, function(x) as.data.frame(otu_table(x)))
# for (i in 2:length(phylo_list)) {
#   # print(i)
#   tmp <- otu_table(phylo_list[[i]])
#   tmp <- data.frame(taxa = as.numeric(rownames(tmp)), tmp[,1])
#   colnames(tmp) <- c("taxa", paste('s', i))
#   mat <- full_join(mat, tmp, by = c("taxa" = "taxa"))
#   dim(mat)
# }

phylo_list_df <- list()
for(i in 1:length(phylo_list)) {
  print(i)
  mtx1 <- phylo_list[[i]] %>% otu_table() %>% as.data.frame()
  mtx1 <- data.frame(ID = rownames(mtx1), mtx1)
  colnames(mtx1) <- c("ID", paste0('s', i))
  phylo_list_df <- c(phylo_list_df, list(mtx1))
}
phylo_list_df[[1]] %>% head
# Combine all elements in a list into a data frame, merging by both IDs. Time consuming, over 5 hours
mtx_biom_data_all_df <- phylo_list_df %>% purrr::reduce(full_join, by = c("ID"))
head(mtx_biom_data_all_df)
mtx_biom_data_all_df[is.na(mtx_biom_data_all_df)] <- 0
mat <- mtx_biom_data_all_df

rownames(mat) <- mat$ID
colnames(mat)[-1] <- files
# mat[is.na(mat)] <- 0
mat.taxa <- mat$ID
mat <- mat[,-1]
mat <- as.matrix(mat)
# get which files are in metadata
idx <- match(files, meta$file_name)


```

## Tax table


```{r}
# Make taxonomy table
# Get taxonomy column
mtx_tax_table <- as.character(green$V2)
# Split the combined strings, and combine them into data frame
mtx_tax_table <- sapply(mtx_tax_table, function(x) strsplit(x, "; ")) %>% unname %>% do.call(rbind, .)


# A function to take column i, extract taxa level prefix, return unique prefixes
# Made for sanity check - each column should return only one taxa level ID
check_taxa_level <- function(mtx_tax_table, i) {
  sapply(mtx_tax_table[, i], function(x) strsplit(x, "__")[[1]][1]) %>% unname %>% unique
}
# Actually do sanity check - should be single letters corresponding to
# Kingdom   Phylum          Class          Order          Family          Genus        Species
for (i in 1:ncol(mtx_tax_table)) {
  check_taxa_level(mtx_tax_table = mtx_tax_table, i) %>% print
}

# A function to take a column and remove taxa level prefix from it
prune_taxa_level <- function(column) {
  sapply(column, function(x) strsplit(x, "__")[[1]][2]) %>% unname
}
# Actually remove prefixes from the columns
mtx_tax_table <- apply(mtx_tax_table, 2, function(x) prune_taxa_level(x))

# Attach column and row names
colnames(mtx_tax_table) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species") # Fixed names
rownames(mtx_tax_table) <- green$V1 # Greengene IDs
mtx_tax_table[1:5, 1:5]
```

## make phyloseq object

```{r}
meta <- as.data.frame(meta[idx,])
rownames(meta) <- meta$file_name

otu <- otu_table(mat, taxa_are_rows = TRUE)
samp <- sample_data(meta)

# order everything
tax.idx <- match(rownames(mtx_tax_table), rownames(mat))
tax.idx <- tax.idx[!is.na(tax.idx)]
taxa <- mtx_tax_table[tax.idx,]

IBD_phyloseq <- phyloseq(otu, samp, taxa)
save(IBD_phyloseq, file = "data/hmp2_phyloseq_16S_ibd.rda")
```

