---
title: "Greengenes"
# author: "Author's Name"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: no
  html_document:
    theme: cerulean
    toc: yes
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Set up the environment
library(knitr)
opts_chunk$set(cache.path='cache/', fig.path='img/', cache=F, tidy=T, fig.keep='high', echo=F, dpi=100, warnings=F, message=F, comment=NA, warning=F, results='as.is', fig.width = 10, fig.height = 6) #out.width=700, 
library(pander)
panderOptions('table.split.table', Inf)
set.seed(1)
library(dplyr)
options(stringsAsFactors = FALSE)
```

```{r}
# Libraries
library(readr)
```

# Settings

```{r}
fileNameIn1  <- "data/99_otu_taxonomy.txt.gz"
fileNameIn2  <- "data/mtx_biom_ID_all.csv" # All IDs from .biom files
```

Greengenes download page: http://greengenes.secondgenome.com/downloads/database/13_5. FTP: ftp://greengenes.microbio.me/greengenes_release/, taxonomy: ftp://greengenes.microbio.me/greengenes_release/gg_13_8_otus/taxonomy/

```
wget ftp://greengenes.microbio.me/greengenes_release/gg_13_8_otus/taxonomy/99_otu_taxonomy.txt
gzip 99_otu_taxonomy.txt
```


```{r}
# Greengenes
mtx_greengenes <- read_tsv(file = fileNameIn1, col_names = FALSE)
head(mtx_greengenes)
# Biom IDs
mtx_biom_ID_all <- read_csv(file = fileNameIn2, col_types = "c")
# Are there any biom ID that is not in Greengenes?
setdiff(mtx_biom_ID_all$mtx_biom_ID_all, mtx_greengenes$X1)
```

