---
title: "OSDF JSON-Schema"
author: "Mikhail Dozmorov"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: no
  html_document:
    theme: cerulean
    toc: yes
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Set up the environment
library(knitr)
opts_chunk$set(cache.path='cache/', fig.path='img/', cache=F, tidy=T, fig.keep='high', echo=F, dpi=100, warnings=F, message=F, comment=NA, warning=F, results='as.is', fig.width = 10, fig.height = 6) #out.width=700, 
library(pander)
panderOptions('table.split.table', Inf)
set.seed(1)
library(dplyr)
options(stringsAsFactors = FALSE)
```

```{r libraries}
library(jsonlite)
library(tibble)
# devtools::install_github("hrbrmstr/jsonview")
library(jsonview)
```

```{r settings}
dataDir <- "osdf-schemas/ihmp/schemas/"
```

```{r}
files <- list.files(dataDir, pattern = "json", full.names = TRUE)
files
mtx <- fromJSON(files[26])
mtx %>% str
mtx_flat <- as.data.frame(mtx)
mtx_tbl <- as_data_frame(mtx_flat)
json_tree_view(mtx)
```

```{r}
json_tree_view(fromJSON("osdf-schemas/ihmp/linkage.json"))
```

